//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class АкцияЗапрос
    {
        public int КодАкция { get; set; }
        public string НазваниеАкция { get; set; }
        public Nullable<System.DateTime> ДатаНачала { get; set; }
        public Nullable<System.DateTime> ДатаОкончания { get; set; }
        public Nullable<int> Скидка { get; set; }
    }
}
