//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Запись
    {
        public Запись()
        {
            this.ОплатаУслуг = new HashSet<ОплатаУслуг>();
        }
    
        public int КодЗапись { get; set; }
        public Nullable<System.DateTime> ДатаЗапись { get; set; }
        public Nullable<int> КодВремя { get; set; }
        public Nullable<int> КодКлиент { get; set; }
        public Nullable<int> КодСотрудник { get; set; }
        public Nullable<int> КодАкция { get; set; }
        public Nullable<int> КодУслуга { get; set; }
    
        public virtual Акция Акция { get; set; }
        public virtual Клиент Клиент { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
        public virtual ТаблицаВремени ТаблицаВремени { get; set; }
        public virtual Услуга Услуга { get; set; }
        public virtual ICollection<ОплатаУслуг> ОплатаУслуг { get; set; }
    }
}
