//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаписьЗапрос1
    {
        public int КодЗапись { get; set; }
        public Nullable<System.DateTime> ДатаЗапись { get; set; }
        public Nullable<int> КодВремя { get; set; }
        public Nullable<int> КодКлиент { get; set; }
        public int КодДолжность { get; set; }
        public Nullable<int> КодСотрудник { get; set; }
        public Nullable<int> КодАкция { get; set; }
    }
}
