//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка
    {
        public int КодЗаявки { get; set; }
        public string Имя { get; set; }
        public System.DateTime Дата { get; set; }
        public int КодУслуга { get; set; }
        public string Телефон { get; set; }
        public string Email { get; set; }
        public string Примечание { get; set; }
    
        public virtual Услуга Услуга { get; set; }
    }
}
