//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ОКОНЧАТЕЛЬНАЯСТОИМОСТЬ
    {
        public int КодЗапись { get; set; }
        public Nullable<System.DateTime> ДатаЗапись { get; set; }
        public string ФИОклиент { get; set; }
        public Nullable<decimal> СтоимостьУслуг { get; set; }
        public int КодАкция { get; set; }
        public Nullable<int> Скидка { get; set; }
        public Nullable<decimal> ОкончательнаяСтоимость1 { get; set; }
    }
}
