//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Остаток
    {
        public int КодМатериал { get; set; }
        public string НаименованиеМатериал { get; set; }
        public Nullable<int> СуммаПрихода { get; set; }
        public Nullable<int> СуммаРасхода { get; set; }
        public Nullable<int> Остаток1 { get; set; }
    }
}
