//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставщик
    {
        public Поставщик()
        {
            this.Приход = new HashSet<Приход>();
        }
    
        public int КодПоставщик { get; set; }
        public string НаименованиеПоставщик { get; set; }
        public string ТелефонПоставщик { get; set; }
        public string АдресПоставщик { get; set; }
        public string EmailПоставщик { get; set; }
    
        public virtual ICollection<Приход> Приход { get; set; }
    }
}
