//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class РасходЗапрос
    {
        public int КодРасход { get; set; }
        public Nullable<int> КодМатериал { get; set; }
        public Nullable<int> КодСотрудник { get; set; }
        public Nullable<int> КоличествоРасход { get; set; }
        public Nullable<System.DateTime> ДатаРасход { get; set; }
    }
}
