//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Разряды
    {
        public Разряды()
        {
            this.Тариф = new HashSet<Тариф>();
        }
    
        public int КодРазряд { get; set; }
        public Nullable<int> Разряд { get; set; }
    
        public virtual ICollection<Тариф> Тариф { get; set; }
    }
}
