//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class СоставПрихода
    {
        public int КодЕдиницы { get; set; }
        public Nullable<int> КодПриход { get; set; }
        public Nullable<int> КодМатериал { get; set; }
        public Nullable<int> КоличествоПриход { get; set; }
        public Nullable<decimal> ЦенаМатериал { get; set; }
    
        public virtual Материал Материал { get; set; }
        public virtual Приход Приход { get; set; }
    }
}
