//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        public Сотрудник()
        {
            this.Запись = new HashSet<Запись>();
            this.Расход = new HashSet<Расход>();
            this.Табель = new HashSet<Табель>();
        }
    
        public int КодСотрудник { get; set; }
        public string ФИОсотрудник { get; set; }
        public Nullable<int> КодТариф { get; set; }
        public string ТелефонСотрудник { get; set; }
        public string АдресСотрудник { get; set; }
        public Nullable<System.DateTime> ДатаРожденияСотрудник { get; set; }
        public string ПримечаниеСотрудник { get; set; }
    
        public virtual ICollection<Запись> Запись { get; set; }
        public virtual ICollection<Расход> Расход { get; set; }
        public virtual Тариф Тариф { get; set; }
        public virtual ICollection<Табель> Табель { get; set; }
    }
}
