//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class СотрудникЗапрос
    {
        public int КодСотрудник { get; set; }
        public string ФИОсотрудник { get; set; }
        public Nullable<int> КодТариф { get; set; }
        public string ТелефонСотрудник { get; set; }
        public string АдресСотрудник { get; set; }
        public Nullable<System.DateTime> ДатаРожденияСотрудник { get; set; }
        public string ПримечаниеСотрудник { get; set; }
        public string Должность { get; set; }
        public Nullable<int> Разряд { get; set; }
        public int КодДолжность { get; set; }
        public int КодРазряд { get; set; }
        public Nullable<decimal> Ставка { get; set; }
    }
}
