//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тариф
    {
        public Тариф()
        {
            this.Сотрудник = new HashSet<Сотрудник>();
        }
    
        public int КодТариф { get; set; }
        public Nullable<int> КодРазряд { get; set; }
        public Nullable<int> КодДолжность { get; set; }
        public Nullable<decimal> Ставка { get; set; }
    
        public virtual Должность Должность { get; set; }
        public virtual Разряды Разряды { get; set; }
        public virtual ICollection<Сотрудник> Сотрудник { get; set; }
    }
}
