//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Табель
    {
        public int КодТабель { get; set; }
        public Nullable<int> КодСотрудник { get; set; }
        public Nullable<System.DateTime> ДатаВыхода { get; set; }
        public Nullable<int> КоличествоОтработанныхЧасов { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
