//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class УслугаЗапрос
    {
        public int КодУслуга { get; set; }
        public string НаименованиеУслуга { get; set; }
        public Nullable<int> КодКатегория { get; set; }
        public Nullable<decimal> ЦенаУслуги { get; set; }
        public string Описание { get; set; }
    }
}
