//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуга
    {
        public Услуга()
        {
            this.Запись = new HashSet<Запись>();
            this.Заявка = new HashSet<Заявка>();
        }
    
        public int КодУслуга { get; set; }
        public string НаименованиеУслуга { get; set; }
        public Nullable<int> КодКатегория { get; set; }
        public Nullable<decimal> ЦенаУслуги { get; set; }
        public string Описание { get; set; }
    
        public virtual ICollection<Запись> Запись { get; set; }
        public virtual ICollection<Заявка> Заявка { get; set; }
        public virtual КатегорияУслуги КатегорияУслуги { get; set; }
    }
}
